# List of worlds where the plugin functionality is disabled
blocked_world:
  - example_world
  - another_world

# Configuration for the title displayed when entering a new biome
title:
  enabled: true
  message_prefix: "You are entering: "
  fade_in: 10
  stay: 70
  fade_out: 20

# Configuration for sending a message in chat when entering a new biome
message:
  enabled: true
  text: "Entered biome: %biome%"

# Configuration for playing a sound when entering a new biome
sound:
  enabled: true
  type: "ENTITY_PLAYER_LEVELUP"
  volume: 1.0
  pitch: 1.0

# Biome names configuration
biome_names:
  badlands: "&cğŸª¨ Badlands"
  bamboo_jungle: "&2ğŸ‹ Bamboo Jungle"
  basalt_deltas: "&8ğŸª¨ Basalt Deltas"
  beach: "&eğŸ– Beach"
  birch_forest: "&fğŸŒ³ Birch Forest"
  cherry_grove: "&dğŸŒ¸ Cherry Grove"
  cold_ocean: "&9ğŸŒŠ Cold Ocean"
  crimson_forest: "&cğŸŒ³ Crimson Forest"
  dark_forest: "&1ğŸŒ² Dark Forest"
  deep_cold_ocean: "&9â„ Deep Cold Ocean"
  deep_dark: "&3ğŸ–¤ Deep Dark"
  deep_frozen_ocean: "&bâ„ Deep Frozen Ocean"
  deep_lukewarm_ocean: "&bğŸŒŠ Deep Lukewarm Ocean"
  deep_ocean: "&9ğŸŒŠ Deep Ocean"
  desert: "&6ğŸœ Desert"
  dripstone_caves: "&7â› Dripstone Caves"
  end_barrens: "&5ğŸŒŒ End Barrens"
  end_highlands: "&5ğŸ” End Highlands"
  end_midlands: "&5ğŸ End Midlands"
  eroded_badlands: "&cğŸœ Eroded Badlands"
  flower_forest: "&dğŸŒ» Flower Forest"
  forest: "&2ğŸŒ² Forest"
  frozen_ocean: "&bâ„ Frozen Ocean"
  frozen_peaks: "&fğŸ” Frozen Peaks"
  frozen_river: "&9â„ Frozen River"
  grove: "&2ğŸŒ³ Grove"
  ice_spikes: "&bğŸ§Š Ice Spikes"
  jagged_peaks: "&8â›° Jagged Peaks"
  jungle: "&2ğŸŒ´ Jungle"
  lukewarm_ocean: "&3ğŸŒŠ Lukewarm Ocean"
  lush_caves: "&2ğŸŒ¿ Lush Caves"
  mangrove_swamp: "&2ğŸŒ´ Mangrove Swamp"
  meadow: "&ağŸŒ¼ Meadow"
  mushroom_fields: "&dğŸ„ Mushroom Fields"
  nether_wastes: "&4ğŸ”¥ Nether Wastes"
  ocean: "&9ğŸŒŠ Ocean"
  old_growth_birch_forest: "&fğŸŒ³ Old Growth Birch Forest"
  old_growth_pine_taiga: "&2ğŸŒ² Old Growth Pine Taiga"
  old_growth_spruce_taiga: "&2ğŸŒ² Old Growth Spruce Taiga"
  plains: "&eğŸŒ¾ Plains"
  river: "&9ğŸŒŠ River"
  savanna: "&eğŸŒ¾ Savanna"
  savanna_plateau: "&eâ›° Savanna Plateau"
  small_end_islands: "&5ğŸ Small End Islands"
  snowy_beach: "&fâ›± Snowy Beach"
  snowy_plains: "&fâ„ Snowy Plains"
  snowy_slopes: "&fğŸ” Snowy Slopes"
  snowy_taiga: "&fğŸŒ² Snowy Taiga"
  soul_sand_valley: "&4ğŸœ Soul Sand Valley"
  sparse_jungle: "&2ğŸŒ´ Sparse Jungle"
  stony_peaks: "&8ğŸ” Stony Peaks"
  stony_shore: "&7ğŸ– Stony Shore"
  sunflower_plains: "&eğŸŒ» Sunflower Plains"
  swamp: "&2ğŸŒ¿ Swamp"
  taiga: "&2ğŸŒ² Taiga"
  the_end: "&5ğŸŒŒ The End"
  the_void: "&8ğŸŒŒ The Void"
  warm_ocean: "&bğŸŒŠ Warm Ocean"
  warped_forest: "&5ğŸŒ³ Warped Forest"
  windswept_forest: "&2ğŸŒ³ Windswept Forest"
  windswept_gravelly_hills: "&7â›° Windswept Gravelly Hills"
  windswept_hills: "&7ğŸ” Windswept Hills"
  windswept_savanna: "&eğŸŒ¾ Windswept Savanna"
  wooded_badlands: "&cğŸŒ² Wooded Badlands"