# List of worlds where the plugin functionality is disabled
blocked_world:
  - example_world
  - another_world

# Configuration for the title displayed when entering a new biome
title:
  enabled: true
  message_prefix: "You are entering: "
  fade_in: 10
  stay: 70
  fade_out: 20

# Configuration for sending a message in chat when entering a new biome
message:
  enabled: true
  text: "Entered biome: %biome%"

# Configuration for playing a sound when entering a new biome
sound:
  enabled: true
  volume: 1.0
  pitch: 1.0

# Biome configuration
biome_config:
  badlands:
    display_name: "&cğŸª¨ Badlands"
    sound: "BLOCK_SAND_BREAK"
  bamboo_jungle:
    display_name: "&2ğŸ‹ Bamboo Jungle"
    sound: "BLOCK_BAMBOO_BREAK"
  basalt_deltas:
    display_name: "&8ğŸª¨ Basalt Deltas"
    sound: "BLOCK_BASALT_BREAK"
  beach:
    display_name: "&eğŸ– Beach"
    sound: "ENTITY_TURTLE_EGG_HATCH"
  birch_forest:
    display_name: "&fğŸŒ³ Birch Forest"
    sound: "BLOCK_WOOD_BREAK"
  cherry_grove:
    display_name: "&dğŸŒ¸ Cherry Grove"
    sound: "BLOCK_CHERRY_LEAVES_BREAK"
  cold_ocean:
    display_name: "&9ğŸŒŠ Cold Ocean"
    sound: "ENTITY_DOLPHIN_SPLASH"
  crimson_forest:
    display_name: "&cğŸŒ³ Crimson Forest"
    sound: "BLOCK_NETHER_WART_BREAK"
  dark_forest:
    display_name: "&1ğŸŒ² Dark Forest"
    sound: "ENTITY_WOLF_HOWL"
  deep_cold_ocean:
    display_name: "&9â„ Deep Cold Ocean"
    sound: "ENTITY_GUARDIAN_AMBIENT"
  deep_dark:
    display_name: "&3ğŸ–¤ Deep Dark"
    sound: "ENTITY_WARDEN_AMBIENT"
  deep_frozen_ocean:
    display_name: "&bâ„ Deep Frozen Ocean"
    sound: "BLOCK_GLASS_BREAK"
  deep_lukewarm_ocean:
    display_name: "&bğŸŒŠ Deep Lukewarm Ocean"
    sound: "ENTITY_SQUID_SQUIRT"
  deep_ocean:
    display_name: "&9ğŸŒŠ Deep Ocean"
    sound: "ENTITY_DROWNED_AMBIENT"
  desert:
    display_name: "&6ğŸœ Desert"
    sound: "BLOCK_SAND_BREAK"
  dripstone_caves:
    display_name: "&7â› Dripstone Caves"
    sound: "BLOCK_DRIPSTONE_BLOCK_BREAK"
  end_barrens:
    display_name: "&5ğŸŒŒ End Barrens"
    sound: "ENTITY_ENDERMAN_AMBIENT"
  end_highlands:
    display_name: "&5ğŸ” End Highlands"
    sound: "ENTITY_ENDER_DRAGON_FLAP"
  end_midlands:
    display_name: "&5ğŸ End Midlands"
    sound: "ENTITY_SHULKER_AMBIENT"
  eroded_badlands:
    display_name: "&cğŸœ Eroded Badlands"
    sound: "BLOCK_SAND_BREAK"
  flower_forest:
    display_name: "&dğŸŒ» Flower Forest"
    sound: "BLOCK_GRASS_BREAK"
  forest:
    display_name: "&2ğŸŒ² Forest"
    sound: "ENTITY_FOX_AMBIENT"
  frozen_ocean:
    display_name: "&bâ„ Frozen Ocean"
    sound: "BLOCK_GLASS_BREAK"
  frozen_peaks:
    display_name: "&fğŸ” Frozen Peaks"
    sound: "BLOCK_POWDER_SNOW_BREAK"
  frozen_river:
    display_name: "&9â„ Frozen River"
    sound: "BLOCK_GLASS_BREAK"
  grove:
    display_name: "&2ğŸŒ³ Grove"
    sound: "ENTITY_POLAR_BEAR_AMBIENT"
  ice_spikes:
    display_name: "&bğŸ§Š Ice Spikes"
    sound: "BLOCK_GLASS_BREAK"
  jagged_peaks:
    display_name: "&8â›° Jagged Peaks"
    sound: "ENTITY_GOAT_AMBIENT"
  jungle:
    display_name: "&2ğŸŒ´ Jungle"
    sound: "ENTITY_PARROT_AMBIENT"
  lukewarm_ocean:
    display_name: "&3ğŸŒŠ Lukewarm Ocean"
    sound: "ENTITY_TROPICAL_FISH_AMBIENT"
  lush_caves:
    display_name: "&2ğŸŒ¿ Lush Caves"
    sound: "BLOCK_FLOWERING_AZALEA_BREAK"
  mangrove_swamp:
    display_name: "&2ğŸŒ´ Mangrove Swamp"
    sound: "ENTITY_FROG_AMBIENT"
  meadow:
    display_name: "&ağŸŒ¼ Meadow"
    sound: "ENTITY_BEE_POLLINATE"
  mushroom_fields:
    display_name: "&dğŸ„ Mushroom Fields"
    sound: "BLOCK_FUNGUS_BREAK"
  nether_wastes:
    display_name: "&4ğŸ”¥ Nether Wastes"
    sound: "ENTITY_GHAST_AMBIENT"
  ocean:
    display_name: "&9ğŸŒŠ Ocean"
    sound: "ENTITY_DOLPHIN_SPLASH"
  old_growth_birch_forest:
    display_name: "&fğŸŒ³ Old Growth Birch Forest"
    sound: "BLOCK_WOOD_BREAK"
  old_growth_pine_taiga:
    display_name: "&2ğŸŒ² Old Growth Pine Taiga"
    sound: "ENTITY_FOX_AMBIENT"
  old_growth_spruce_taiga:
    display_name: "&2ğŸŒ² Old Growth Spruce Taiga"
    sound: "ENTITY_WOLF_AMBIENT"
  plains:
    display_name: "&eğŸŒ¾ Plains"
    sound: "ENTITY_COW_AMBIENT"
  river:
    display_name: "&9ğŸŒŠ River"
    sound: "ENTITY_FISH_SWIM"
  savanna:
    display_name: "&eğŸŒ¾ Savanna"
    sound: "ENTITY_HORSE_AMBIENT"
  savanna_plateau:
    display_name: "&eâ›° Savanna Plateau"
    sound: "ENTITY_LLAMA_AMBIENT"
  small_end_islands:
    display_name: "&5ğŸ Small End Islands"
    sound: "ENTITY_ENDERMAN_TELEPORT"
  snowy_beach:
    display_name: "&fâ›± Snowy Beach"
    sound: "BLOCK_SNOW_BREAK"
  snowy_plains:
    display_name: "&fâ„ Snowy Plains"
    sound: "BLOCK_SNOW_BREAK"
  snowy_slopes:
    display_name: "&fğŸ” Snowy Slopes"
    sound: "BLOCK_POWDER_SNOW_BREAK"
  snowy_taiga:
    display_name: "&fğŸŒ² Snowy Taiga"
    sound: "ENTITY_WOLF_AMBIENT"
  soul_sand_valley:
    display_name: "&4ğŸœ Soul Sand Valley"
    sound: "BLOCK_SOUL_SAND_BREAK"
  sparse_jungle:
    display_name: "&2ğŸŒ´ Sparse Jungle"
    sound: "ENTITY_PARROT_AMBIENT"
  stony_peaks:
    display_name: "&8ğŸ” Stony Peaks"
    sound: "BLOCK_STONE_BREAK"
  stony_shore:
    display_name: "&7ğŸ– Stony Shore"
    sound: "BLOCK_STONE_BREAK"
  sunflower_plains:
    display_name: "&eğŸŒ» Sunflower Plains"
    sound: "BLOCK_GRASS_BREAK"
  swamp:
    display_name: "&2ğŸŒ¿ Swamp"
    sound: "ENTITY_SLIME_SQUISH"
  taiga:
    display_name: "&2ğŸŒ² Taiga"
    sound: "ENTITY_FOX_AMBIENT"
  the_end:
    display_name: "&5ğŸŒŒ The End"
    sound: "ENTITY_ENDER_DRAGON_AMBIENT"
  the_void:
    display_name: "&8ğŸŒŒ The Void"
    sound: "BLOCK_END_PORTAL_FRAME_FILL"
  warm_ocean:
    display_name: "&bğŸŒŠ Warm Ocean"
    sound: "ENTITY_TROPICAL_FISH_AMBIENT"
  warped_forest:
    display_name: "&5ğŸŒ³ Warped Forest"
    sound: "BLOCK_WARPED_STEM_BREAK"
  windswept_forest:
    display_name: "&2ğŸŒ³ Windswept Forest"
    sound: "ENTITY_FOX_AMBIENT"
  windswept_gravelly_hills:
    display_name: "&7â›° Windswept Gravelly Hills"
    sound: "BLOCK_GRAVEL_BREAK"
  windswept_hills:
    display_name: "&7ğŸ” Windswept Hills"
    sound: "ENTITY_GOAT_AMBIENT"
  windswept_savanna:
    display_name: "&eğŸŒ¾ Windswept Savanna"
    sound: "ENTITY_HORSE_AMBIENT"
  wooded_badlands:
    display_name: "&cğŸŒ² Wooded Badlands"
    sound: "BLOCK_ROOTED_DIRT_BREAK"